version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: anwesende_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - ${ANW_HOSTDIR_DJANGO_LOG}:/djangolog:Z
    env_file:
      - .envs/.local
    ports:
      - "8006:8000"  # host:container
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: anwesende_production_postgres
    container_name: postgres
    volumes:
      - ${ANW_HOSTDIR_POSTGRES_DATA}:/var/lib/postgresql/data:Z
      - ${ANW_HOSTDIR_POSTGRES_BACKUP}:/backups:z
    env_file:
      - .envs/.local
